#!/usr/bin/env node
/*
 * The Arch package, written from the release rather than by hand.
 *
 * An AUR package is two files that repeat facts held somewhere else: a version, a checksum, a
 * description and a licence. Kept by hand they go stale one release after somebody stops paying
 * attention, and a stale PKGBUILD fails at the checksum, which reads to the user as "this
 * project is abandoned" rather than "nobody regenerated a file".
 *
 * So both are generated. The checksum does not need the 130 MB download: electron-builder
 * publishes latest-linux.yml beside the AppImage with the sha512 in it, which is the same digest
 * the updater checks, so the package and the in-app update trust exactly the same number.
 *
 *   node tools/gen-aur.js              the newest published release
 *   node tools/gen-aur.js 2.6.4        a particular one
 *
 * Publishing is a separate act and needs an AUR account: clone ssh://aur@aur.archlinux.org/
 * dota2-mod-manager-appimage.git, copy both files in, commit, push. Nothing here touches it.
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const OUT = path.resolve(__dirname, '..', 'packaging', 'aur');
const REPO = 'dota2modmanager/dota2-mod-manager';
const PKGNAME = 'dota2-mod-manager-appimage';

function get(url, depth = 0) {
  return new Promise((resolve, reject) => {
    if (depth > 5) return reject(new Error('too many redirects'));
    https.get(url, { headers: { 'user-agent': 'gen-aur' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        return resolve(get(new URL(res.headers.location, url).toString(), depth + 1));
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(`${res.statusCode} for ${url}`));
      }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    }).on('error', reject);
  });
}

/** Version and AppImage digest, taken from the manifest the app's own updater reads. */
async function release(version) {
  const at = version
    ? `https://github.com/${REPO}/releases/download/v${version}/latest-linux.yml`
    : `https://github.com/${REPO}/releases/latest/download/latest-linux.yml`;
  const yml = await get(at);

  const v = /^version:\s*(.+)$/m.exec(yml);
  // the top-level sha512 is the one for `path:`, which is the AppImage itself
  const sha = /^sha512:\s*(\S+)$/m.exec(yml);
  if (!v || !sha) throw new Error(`latest-linux.yml at ${at} is not the shape this expects`);

  return {
    version: v[1].trim(),
    // base64 in the manifest, hex in a PKGBUILD, same bytes
    sha512: Buffer.from(sha[1].trim(), 'base64').toString('hex'),
  };
}

const FIELDS = (v) => ({
  pkgname: PKGNAME,
  pkgver: v.version,
  pkgrel: '1',
  pkgdesc: 'Mods for Dota 2 without the file juggling: browse, install, toggle and share cosmetic mods from the open D2PFX catalog',
  arch: 'x86_64',
  url: 'https://dota2modmanager.com',
  license: 'GPL-3.0-or-later',
});

function pkgbuild(v) {
  const f = FIELDS(v);
  return `# Maintainer: TheFleece <linnik.misha.2007@gmail.com>
#
# Generated by tools/gen-aur.js in the upstream repository. Edit that, not this.
# The checksum comes from latest-linux.yml, the same manifest the app's own updater verifies
# against, so this package and an in-app update trust the same digest.

pkgname=${f.pkgname}
_appname=dota2-mod-manager
pkgver=${f.pkgver}
pkgrel=${f.pkgrel}
pkgdesc="${f.pkgdesc}"
arch=('${f.arch}')
url="${f.url}"
license=('${f.license}')
depends=('gtk3' 'nss' 'alsa-lib' 'libxtst' 'libsecret' 'hicolor-icon-theme')
options=('!strip')
source=("\${_appname}-\${pkgver}.AppImage::https://github.com/${REPO}/releases/download/v\${pkgver}/Dota-2-Mod-Manager.AppImage")
sha512sums=('${v.sha512}')
noextract=("\${_appname}-\${pkgver}.AppImage")

prepare() {
  # Unpacked rather than run through FUSE: one less runtime dependency, and the desktop entry
  # and icons end up where a desktop environment looks for them.
  chmod +x "\${_appname}-\${pkgver}.AppImage"
  "./\${_appname}-\${pkgver}.AppImage" --appimage-extract >/dev/null

  # The entry inside an AppImage points at AppRun; here it points at the installed binary.
  sed -i -E 's|^Exec=.*|Exec=/usr/bin/'"\${_appname}"' %U|' squashfs-root/*.desktop
  sed -i -E 's|^Icon=.*|Icon='"\${_appname}"'|' squashfs-root/*.desktop
}

package() {
  install -dm755 "\${pkgdir}/opt/\${_appname}"
  cp -a squashfs-root/. "\${pkgdir}/opt/\${_appname}/"

  # AppImage extraction leaves the tree group- and world-writable on some setups
  chmod -R go-w "\${pkgdir}/opt/\${_appname}"
  chmod 755 "\${pkgdir}/opt/\${_appname}/AppRun"

  # No setuid chrome-sandbox. Arch allows unprivileged user namespaces, which is the sandbox
  # Electron reaches for first, and a setuid root binary is not a thing to add to somebody's
  # system so a mod manager can start half a second earlier.
  rm -f "\${pkgdir}/opt/\${_appname}/chrome-sandbox"

  install -dm755 "\${pkgdir}/usr/bin"
  ln -s "/opt/\${_appname}/AppRun" "\${pkgdir}/usr/bin/\${_appname}"

  install -Dm644 squashfs-root/*.desktop -t "\${pkgdir}/usr/share/applications/"

  # electron-builder writes the sized icons under usr/share/icons and one at the root. Take the
  # set where there is one, fall back to the single file rather than shipping no icon at all.
  if [ -d squashfs-root/usr/share/icons ]; then
    install -dm755 "\${pkgdir}/usr/share/icons"
    cp -a squashfs-root/usr/share/icons/. "\${pkgdir}/usr/share/icons/"
  elif [ -f "squashfs-root/\${_appname}.png" ]; then
    install -Dm644 "squashfs-root/\${_appname}.png" \\
      "\${pkgdir}/usr/share/icons/hicolor/512x512/apps/\${_appname}.png"
  fi
}
`;
}

/** .SRCINFO is the machine-readable half, and the AUR refuses a push where it disagrees. */
function srcinfo(v) {
  const f = FIELDS(v);
  return `pkgbase = ${f.pkgname}
\tpkgdesc = ${f.pkgdesc}
\tpkgver = ${f.pkgver}
\tpkgrel = ${f.pkgrel}
\turl = ${f.url}
\tarch = ${f.arch}
\tlicense = ${f.license}
\tdepends = gtk3
\tdepends = nss
\tdepends = alsa-lib
\tdepends = libxtst
\tdepends = libsecret
\tdepends = hicolor-icon-theme
\toptions = !strip
\tnoextract = dota2-mod-manager-${f.pkgver}.AppImage
\tsource = dota2-mod-manager-${f.pkgver}.AppImage::https://github.com/${REPO}/releases/download/v${f.pkgver}/Dota-2-Mod-Manager.AppImage
\tsha512sums = ${v.sha512}

pkgname = ${f.pkgname}
`;
}

async function main() {
  const asked = process.argv[2] && process.argv[2].replace(/^v/, '');
  const v = await release(asked);

  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, 'PKGBUILD'), pkgbuild(v));
  fs.writeFileSync(path.join(OUT, '.SRCINFO'), srcinfo(v));
  console.log(`packaging/aur written for ${v.version}`);
  console.log(`sha512 ${v.sha512.slice(0, 24)}... (from latest-linux.yml, no download)`);
}

if (require.main === module) {
  main().catch((e) => { console.error(e.message); process.exit(1); });
}

module.exports = { pkgbuild, srcinfo, release };
